language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8

install:
  - pip install .
  - pip install coveralls pytest-cov

# command to run tests
script:
  - coverage run --rcfile=.coveragerc --source demandlib -m py.test
  - coverage report

after_success:
  - coveralls

